### ISSUE TITLE
Config option for table name

### ISSUE THREAD

**Issue by lasseal** [spatie/activitylog#13]
Is there a config option to choose a different table name than the default "activity_log" for the migration? Would be great to have.

**Comment by sebastiandedeyne** [comment]
I'll look into this next week.

**Comment by sebastiandedeyne** [comment]
Had a look, the problem is that this would require a dynamic table name in the Activity model, which isn't so simple to set up.

I'm planning on doing some refactoring on this package (probably for 3.0) and will add the option in there. I can't give any guarantee on when this is going to happen though.

**Comment by freekmurze** [comment]
Like @sebastiandedeyne siad we'll add it in the next major version of the package. Unfortunately we can't give you an ETA on when that might happen.

If you need this submit a PR.
