### ISSUE TITLE
Migrations duplicating

### ISSUE THREAD

**Issue by a-komarev** [spatie/activitylog#18]
Hello, Freek.

Because in ServiceProvider there is no checks if migration was already published before it's duplucating after each `vendor:publish` command.

**Comment by freekmurze** [comment]
I don't recommend using `vendor:publish` without flags. It's a good idea to always specify the service provider of which you want to assets to install eg:
```bash
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider"
```
Of course you should execute that command only once (otherwise you'll still get duplicate migrations).

I could solve this problem not using a timestamp in the name of the migration, but I prefer a timestamp being there.

**Comment by a-komarev** [comment]
I've removed timestamps in my packages too and performing a check if current classname already exists in migrations directory before publishing it.
